#!/usr/bin/env bash

# 当前脚本所在目录
HOME_DIR="$( cd "$( dirname "$0"  )" && pwd  )"
ACTION=${1}

ENV=${HOME_DIR}/env.yaml
ENV_SAMPLE=${HOME_DIR}/tests/env.sample.yaml
PHPUNIT=${HOME_DIR}/vendor/bin/phpunit
PHPDOC=${HOME_DIR}/vendor/bin/phpdoc



# 检查环境配置文件是否存在
if [ ! -f ${ENV} ]; then
    cp ${ENV_SAMPLE} ${ENV}
fi


case ${ACTION} in
    "test") # 测试文件/文件夹/全部
        FILE=${2}
        ${PHPUNIT} ${FILE}
    ;;
    "testsuite") # 测试套件
        SUIT_NAME=${2}
        ${PHPUNIT} --testsuite ${SUIT_NAME}
    ;;
    "doc") # 输出文档
        ${PHPDOC}
    ;;
esac