#!/usr/bin/env bash

# 当前脚本所在目录
HOME_DIR="$( cd "$( dirname "$0"  )" && pwd  )"
ACTION=${1}

ENV=${HOME_DIR}/tests/env.yaml
ENV_SAMPLE=${HOME_DIR}/env.sample.yaml
PHPUNIT=${HOME_DIR}/vendor/bin/phpunit
PHPDOC=${HOME_DIR}/vendor/bin/phpdoc



# 检查环境配置文件是否存在
if [ ! -f ${ENV} ]; then
    cp ${ENV_SAMPLE} ${ENV}
fi


case ${ACTION} in
    "test") # 测试文件/文件夹/全部
        FILE=${2}
        ${PHPUNIT} ${FILE}
    ;;
    "testsuite") # 测试套件
        SUIT_NAME=${2}
        ${PHPUNIT} --testsuite ${SUIT_NAME}
    ;;
    "doc") # 输出文档
        ${PHPDOC}
    ;;

    "rsa")
    rsa_private_key=${HOME_DIR}/runtime/rsa_private.key
    private_key=${HOME_DIR}/runtime/private.key
    rsa_rsa_public=${HOME_DIR}/runtime/rsa_public.key

    # 生成 RSA 私钥
    openssl genrsa -out ${rsa_private_key} 1024
    #
    openssl pkcs8 -topk8 -inform PEM -in ${rsa_private_key} -outform PEM -nocrypt -out ${private_key}
    # 生成 RSA 公钥
    openssl rsa -in ${rsa_private_key} -pubout -out ${rsa_rsa_public}
    ;;

esac